### ISSUE TITLE
Gracefully handle server and connection errors

### ISSUE THREAD

**Issue by miohtama** [BlockIo/block_io-python#8]
Looks like block.io API servers have issues (getting Bad Gateway now and then). This makes block.io Python client melt in smoldering ashes. Like:

      File "/home/ubuntu/src/bitbucket.org/miohtama/cryptoassets/venv/lib/python3.4/site-packages/block_io/__init__.py", line 253, in api_call
        if ('error_message' in response['data'].keys()):
    KeyError: 'data'
    [2015-01-12 13:27:37,608] cryptoassets.core.tools.broadcast send_broadcasts():183   'data'
    Traceback (most recent call last):
      File "/home/ubuntu/src/bitbucket.org/miohtama/cryptoassets/cryptoassets/core/tools/broadcast.py", line 177, in send_broadcasts
        txid, fee = self.backend.send(outgoing, "Outgoing broadcast {}".format(b.id))
      File "/home/ubuntu/src/bitbucket.org/miohtama/cryptoassets/cryptoassets/core/backend/blockio.py", line 136, in send
        resp = self.block_io.withdraw(amounts=",".join(amounts), to_addresses=",".join(addresses))
      File "/home/ubuntu/src/bitbucket.org/miohtama/cryptoassets/venv/lib/python3.4/site-packages/block_io/__init__.py", line 146, in withdraw_hook
        return self.withdraw_meta(attr, **kwargs)
      File "/home/ubuntu/src/bitbucket.org/miohtama/cryptoassets/venv/lib/python3.4/site-packages/block_io/__init__.py", line 224, in withdraw_meta
        response = self.api_call('sign_and_finalize_withdrawal', **args)
      File "/home/ubuntu/src/bitbucket.org/miohtama/cryptoassets/venv/lib/python3.4/site-packages/block_io/__init__.py", line 253, in api_call
        if ('error_message' in response['data'].keys()):
    KeyError: 'data'

It could be ideal to add some defensive programming to block.io API client, so that it displays friendlier exception *Got 500 Internal Server Error from API server* and possible raise APICallFailed() exception, so that the client application can gracefully handle the situation.

**Comment by doersf** [comment]
Agreed -- issues like this can occur on a public, free infrastructure. Best to handle them gracefully.

Will update here once able.

**Comment by doersf** [comment]
Updated, and version bumped (1c1efc7b902e8c6cd108d1141d20ce86e38df229)
